### ISSUE TITLE
How to work with request for query string odata

### ISSUE THREAD

**Issue by paulinhps** [skwasjer/MockHttp#25]
Hello, I'm not able to make the mock when the query string is about odata. For example:

```
_mockHttp.When(matching => matching
                .RequestUri("*/Invoices")
                .QueryString($"?$filter=(NumAtCard eq '{validNumAtCard}')")
                .Method(HttpMethod.Get)
                .WithoutContent()
            )
                .Respond(HttpStatusCode.OK, JsonSerializer.Serialize(new SapQueryResult<InvoiceDataModel>
                {
                    Value = new[]
                    {
                        expectedInvoice
                    }
                }), "application/json")
                .Verifiable();
```

**Comment by skwasjer** [comment]
Most likely this is because `.RequestUri()` is testing against the full request URI, including query string. Try adding a wildcard to ignore query on the `.RequestUri("*/Invoices?*")` when combining with `.QueryString()`.

I might add an explicit overload `.RequestPath` to differentiate.

**Comment by paulinhps** [comment]
You may not need a new method for this. This approach using the wildcard together with the `.QueryString()` method gave even more emphasis to matching in the business context. Good job!
