### ISSUE TITLE
ClientTimeout should throw a TaskCanceledException with an InnerException of TimeoutException

### ISSUE THREAD

**Issue by benjaminsampica** [skwasjer/MockHttp#49]
HttpClient, starting with .NET Core 3.0, throws `TaskCanceledException` with an inner exception of `TimeoutException`. However, in this libraries `ClientTimeout` it's only throwing a task canceled exception with no inner exception. See https://github.com/dotnet/runtime/issues/21965.

I'm willing to do the PR if this is something you'd like to see added.

**Comment by skwasjer** [comment]
Absolutely, go for it 👍
