### ISSUE TITLE
Setting headers on response cancels the body

### ISSUE THREAD

**Issue by PhotoAtomic** [skwasjer/MockHttp#98]
setting up an httpclient mock like this
<pre> handlerMock
     .When(request => request
         .Method(HttpMethod.Post)
         .RequestUri("api/login")                    
         .ContentType("application/json; charset=utf-8")
         .JsonBody(new { username= @"corp\user", password = @"Super.Mari0.Bro$$" })
     )
     .Respond(reply => reply
         .StatusCode(HttpStatusCode.OK)
         .JsonBody(new { username = "user@corp" }, Encoding.UTF8)                    
         .Header("Set-Cookie", "session=abcdefghi==; Expires=Tue, 01 Feb 2024 01:01:01 GMT; Secure; HttpOnly; Path=/")
     );</pre>

doesn't work because the **.JsonBody** method in the Respond lambda resets the headers and **.Header** resets the body so i cannot have the reply i need with both the headers and the body

**Comment by skwasjer** [comment]
Thanks for spotting this, I've pushed a fix based on your repro.

**Comment by skwasjer** [comment]
@PhotoAtomic [v4.3.1](https://github.com/skwasjer/MockHttp/releases/tag/v4.3.1) should be on NuGet in a few.
